# Generated by Django 4.2.16 on 2024-10-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planejamento", "0002_categoria_montante_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="montante_plan",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10
            ),
        ),
    ]
