# Generated by Django 4.2.16 on 2024-10-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planejamento", "0001_initial"),
        ("transacoes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesa",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="planejamento.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="planejamento.categoria"
            ),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
